name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t02-01-01
      id: t02-01-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t02-01-01
        setup-command: make compile
        command: make -s test_01
        input: |-
          3
          120 80 3
          3 2 50
          3 7 2
        expected-output: |-
          40 30
          0 0
          3 1
        comparison-method: exact
        timeout: 1
        max-score: 30
    - name: t02-02-01
      id: t02-02-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t02-02-01
        setup-command: make compile
        command: make -s test_02
        input: |-
          2
          2 8
          3 20
        expected-output: |-
          3
          6
        comparison-method: exact
        timeout: 1
        max-score: 30
    - name: t02-03-01
      id: t02-03-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t02-03-01
        setup-command: make compile
        command: make -s test_02
        input: |-
          1 20
          9 4 6
        expected-output: '6'
        comparison-method: exact
        timeout: 1
        max-score: 40
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T02-01-01_RESULTS: "${{steps.t02-01-01.outputs.result}}"
        T02-02-01_RESULTS: "${{steps.t02-02-01.outputs.result}}"
        T02-03-01_RESULTS: "${{steps.t02-03-01.outputs.result}}"
      with:
        runners: t02-01-01,t02-02-01,t02-03-01
